User secure endpoints
ISTE-500-501-TeamWatchHill/backend pull request #31
Opened 2023-04-05 14:15 UTC by aag7593

add, update and delete users as an admin

2023-04-06 13:55 UTC, vsoler27 commented on routes/user/userSecure.js
> +                if (!validateName(firstName)) {
a lot of these error codes are wrong a 400 means bad request/bad data and a 403 means forbidden/incorrect permissions

2023-04-06 13:55 UTC, vsoler27 commented on routes/user/userSecure.js
> +            console.log("CRAP");
pls remove

2023-04-06 13:55 UTC, vsoler27 commented on routes/user/userSecure.js
> +                res.status(404).json({"error": "Incomplete Input"});
make this one a 400

2023-04-06 13:56 UTC, vsoler27 requested changes
requesting some small changes but overall this looks good

2023-04-06 14:19 UTC, aag7593 commented on routes/user/userSecure.js
> +                if (!validateName(firstName)) {
Ah okay- I'll make those changes

2023-04-06 14:20 UTC, aag7593 commented on routes/user/userSecure.js
> +            console.log("CRAP");
oop

2023-04-11 18:55 UTC, vsoler27 approved these changes

2023-04-14 00:13 UTC, merged