Adding getAll and byID routes.... test em first
ISTE-500-501-TeamWatchHill/backend pull request #9
Opened 2023-03-06 02:16 UTC by aidan-lemay

Finished GET: /games/all endpoint

2023-03-06 02:19 UTC, aidan-lemay commented
Tested and working

2023-03-06 18:03 UTC, abp6318 requested changes
Can we remove the necessity for a token? These are just GETs and requiring a login to see game info seems annoying

2023-03-06 18:10 UTC, abp6318 approved these changes

2023-03-07 18:32 UTC, aidan-lemay commented
Getting some more stuff in main

2023-03-07 18:32 UTC, merged